version: "3.9"

services:
  user-info-service:
    build: .
    ports:
      - "8080:8080"
      - "5050:5050"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/requests

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=requests
    ports:
      - "5432:5432"
    volumes:
      - ./database/sql/create_table.sql:/docker-entrypoint-initdb.d/create_tables.sql