CREATE TABLE IF NOT EXISTS users_requests (
  id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  login VARCHAR(255) UNIQUE NOT NULL,
  request_counter BIGINT DEFAULT 0,

  PRIMARY KEY (id)
  );